FROM nvidia/cuda:10.1-runtime-ubuntu18.04

# Install the base packages.
COPY install_base.sh ./install_base.sh
RUN sh ./install_base.sh && rm ./install_base.sh

# Install the custom packages for which we will switch to the home directory.
WORKDIR /usr/home
COPY install_packages.sh ./install_packages.sh
RUN sh ./install_packages.sh && rm ./install_packages.sh

# Configure the catkin environment.
COPY ./ws ./ws
WORKDIR /usr/home/ws/src/maplab_features/src
SHELL ["/bin/bash", "-c"]
