version: "3"

services:
  maplab:
    build: .
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./features_ws:/maplab
      - ./data:/data
    devices:
      - "/dev/dri:/dev/dri"
    network_mode: host
    stdin_open: true
    tty: true
