# General settings.
input_topic:            '/alphasense_driver_ros/cam0'

output_topic:           '/maplab_features0'

resize_image:           640
debug_detections:       True
debug_tracking:         True

# Feature extraction settings.
feature_extraction:            'external'
min_distance_to_image_border:  30
mask_redetections_thr_px:      7

# Feature tracking settings.
feature_tracking:   'superglue'
num_tracked_points:  600
