# General settings.
input_topic:            '/alphasense/cam0/image_raw,
                         /alphasense/cam1/image_raw,
                         /alphasense/cam2/image_raw,
                         /alphasense/cam3/image_raw,
                         /alphasense/cam4/image_raw'
output_topic:           '/maplab_features0,
                         /maplab_features1,
                         /maplab_features2,
                         /maplab_features3,
                         /maplab_features4'
mask_topic:              ''

resize_input_image:     640
debug_detections:       false
debug_tracking:         false

# Feature extraction settings.
feature_extraction:            'external'
min_distance_to_image_border:  30
mask_redetections_thr_px:      4
pca_descriptors:               true

# Feature tracking settings.
feature_tracking:    'superglue'
num_tracked_points:  1024
